"""Generate Pydantic models from the in-process agent OpenAPI.

Usage:
    cd backend && uv run python scripts/generate_agent_schemas.py

The output is committed at backend/app/agent_comm/generated.py and is the
source of truth for backend -> agent payload typing. Re-run after any change
to agent/agent_app routes or schemas.
"""

from __future__ import annotations

import json
import subprocess
import tempfile
from pathlib import Path

GENERATED_PATH = Path(__file__).resolve().parents[1] / "app" / "agent_comm" / "generated.py"
HEADER = """# AUTO-GENERATED — DO NOT EDIT.
# Regenerate with:
#     cd backend && uv run python scripts/generate_agent_schemas.py
# Source: agent/agent_app via in-process OpenAPI.
"""

_AGENT_DIR = Path(__file__).resolve().parents[2] / "agent"

# Inline script that the agent venv executes to emit OpenAPI JSON to stdout.
_FETCHER = """
import asyncio, json, sys
from httpx import ASGITransport, AsyncClient
from agent_app.main import app

async def main() -> None:
    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://agent.local") as c:
        r = await c.get("/openapi.json")
        r.raise_for_status()
        sys.stdout.write(json.dumps(r.json(), sort_keys=True))

asyncio.run(main())
"""


def _fetch_openapi_via_agent_venv() -> dict[str, object]:
    out = subprocess.run(
        ["uv", "run", "--project", str(_AGENT_DIR), "python", "-c", _FETCHER],
        capture_output=True,
        text=True,
        check=True,
    )
    payload = json.loads(out.stdout)
    assert isinstance(payload, dict)
    return payload


# Public alias so check_agent_schemas can import the right function.
_fetch_openapi = _fetch_openapi_via_agent_venv


def _strip_codegen_header(text: str) -> str:
    """Remove the non-deterministic '# generated by datamodel-codegen:' block.

    datamodel-codegen prepends lines like::

        # generated by datamodel-codegen:
        #   filename:  tmpXXX.json

    These change on every run because the input is a tempfile.  Strip them so
    our stable HEADER is the only preamble and the output is byte-identical
    across runs.
    """
    lines = text.splitlines(keepends=True)
    result: list[str] = []
    skip = False
    for line in lines:
        if line.startswith("# generated by datamodel-codegen"):
            skip = True
            continue
        if skip:
            # Continuation lines of the codegen header start with "#   "
            if line.startswith("#   "):
                continue
            skip = False
        result.append(line)
    return "".join(result)


def _run_codegen(openapi_path: Path, out_path: Path) -> None:
    cmd = [
        "uv",
        "run",
        "datamodel-codegen",
        "--input",
        str(openapi_path),
        "--input-file-type",
        "openapi",
        "--output",
        str(out_path),
        "--output-model-type",
        "pydantic_v2.BaseModel",
        "--use-annotated",
        "--target-python-version",
        "3.12",
        "--use-standard-collections",
        "--use-union-operator",
        "--disable-timestamp",
    ]
    subprocess.run(cmd, check=True)
    # Apply ruff formatting so the committed file matches what pre-commit would produce.
    subprocess.run(["uv", "run", "ruff", "format", str(out_path)], check=True)


def main() -> int:
    openapi_payload = _fetch_openapi_via_agent_venv()
    tmp_dir = Path(tempfile.mkdtemp())
    in_path = tmp_dir / "openapi.json"
    out_path = tmp_dir / "generated.py"
    try:
        in_path.write_text(json.dumps(openapi_payload, sort_keys=True))
        _run_codegen(in_path, out_path)
        raw = out_path.read_text()
        # Strip non-deterministic codegen header lines (e.g. "# generated by datamodel-codegen:",
        # "#   filename:  tmpXXX.json") before prepending our own stable HEADER.
        body = _strip_codegen_header(raw)
        GENERATED_PATH.write_text(HEADER + body)
    finally:
        in_path.unlink(missing_ok=True)
        out_path.unlink(missing_ok=True)
        tmp_dir.rmdir()

    print(f"wrote {GENERATED_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
