"""Migration-aware import-graph manifest.

Grows over the backend domain-layout refactor. Each new phase appends
its domain to ``MIGRATED_DOMAINS`` and removes shims it deletes from
``LEGACY_SHIM_FILES``. Phase 16 cleanup deletes this file entirely.
"""

from __future__ import annotations

# Domains whose code now lives under ``app/<domain>/`` and which the
# import-graph guard enforces deep-import rules against.
MIGRATED_DOMAINS: frozenset[str] = frozenset(
    {
        "auth",
        "analytics",
        "settings",
        "webhooks",
        "events",
        "jobs",
        "grid",
        "plugins",
        "agent_comm",
        "hosts",
        "packs",
        "appium_nodes",
        "devices",
        "sessions",
        "runs",
    }
)

# Files at original paths that re-export from their new home in
# ``app/core/`` or ``app/<domain>/``. The graph guard exempts these
# from all rules so they can keep their cross-cutting
# ``from app.X import ...`` lines until every caller migrates.
# Phase 16 deletes all shims.
LEGACY_SHIM_FILES: frozenset[str] = frozenset(
    {
        # Phase 0a
        "app/metrics.py",
        # Phase 0b
        "app/config.py",
        "app/database.py",
        "app/type_defs.py",
        "app/shutdown.py",
        "app/metrics_recorders.py",
        "app/services/cursor_pagination.py",
        "app/services/csv_export.py",
        # Phase 1
        "app/dependencies.py",
        "app/middleware.py",
        "app/routers/auth.py",
        "app/routers/analytics.py",
        "app/routers/settings.py",
        "app/routers/webhooks.py",
        "app/routers/events.py",
        "app/routers/grid.py",
        "app/routers/plugins.py",
        "app/schemas/auth.py",
        "app/schemas/analytics.py",
        "app/schemas/setting.py",
        "app/schemas/webhook.py",
        "app/schemas/event.py",
        "app/schemas/event_catalog.py",
        "app/schemas/grid.py",
        "app/schemas/health.py",
        "app/schemas/plugin.py",
        "app/security/__init__.py",
        "app/security/dependencies.py",
        "app/services/auth.py",
        "app/services/auth_dependencies.py",
        "app/services/analytics_service.py",
        "app/models/analytics_capacity_snapshot.py",
        "app/services/settings_registry.py",
        "app/services/settings_service.py",
        "app/services/config_service.py",
        "app/models/setting.py",
        "app/models/config_audit_log.py",
        "app/services/webhook_dispatcher.py",
        "app/services/webhook_service.py",
        "app/models/webhook.py",
        "app/models/webhook_delivery.py",
        "app/services/event_bus.py",
        "app/services/event_catalog.py",
        "app/services/system_event_service.py",
        "app/models/system_event.py",
        "app/services/job_queue.py",
        "app/services/job_kind_constants.py",
        "app/services/job_status_constants.py",
        "app/models/job.py",
        "app/services/grid_service.py",
        "app/services/plugin_service.py",
        "app/models/appium_plugin.py",
        "app/agent_client.py",
        "app/services/agent_http_pool.py",
        "app/services/agent_circuit_breaker.py",
        "app/services/agent_operations.py",
        "app/services/agent_error_codes.py",
        "app/services/agent_probe_result.py",
        "app/services/agent_reconfigure_delivery.py",
        "app/services/agent_snapshot.py",
        "app/models/agent_reconfigure_outbox.py",
        "app/routers/hosts.py",
        "app/routers/host_terminal.py",
        "app/services/host_service.py",
        "app/services/host_diagnostics.py",
        "app/services/host_resource_telemetry.py",
        "app/services/host_terminal_audit.py",
        "app/services/host_terminal_proxy.py",
        "app/services/host_versioning.py",
        "app/services/hardware_telemetry.py",
        "app/schemas/host.py",
        "app/models/host.py",
        "app/models/host_resource_sample.py",
        "app/models/host_terminal_session.py",
        "app/models/host_plugin_runtime_status.py",
        "app/routers/driver_packs.py",
        "app/routers/driver_pack_authoring.py",
        "app/routers/driver_pack_export.py",
        "app/routers/driver_pack_templates.py",
        "app/routers/driver_pack_uploads.py",
        "app/routers/agent_driver_packs.py",
        "app/routers/host_driver_pack_features.py",
        "app/services/pack_service.py",
        "app/services/pack_audit_service.py",
        "app/services/pack_capability_service.py",
        "app/services/pack_delete_service.py",
        "app/services/pack_desired_state_service.py",
        "app/services/pack_discovery_service.py",
        "app/services/pack_drain.py",
        "app/services/pack_export_service.py",
        "app/services/pack_feature_dispatch_service.py",
        "app/services/pack_feature_status_service.py",
        "app/services/pack_host_compatibility.py",
        "app/services/pack_ingest_service.py",
        "app/services/pack_lifecycle_service.py",
        "app/services/pack_platform_catalog.py",
        "app/services/pack_platform_resolver.py",
        "app/services/pack_policy_service.py",
        "app/services/pack_release_ordering.py",
        "app/services/pack_release_service.py",
        "app/services/pack_start_shim.py",
        "app/services/pack_status_service.py",
        "app/services/pack_storage_service.py",
        "app/services/pack_template_service.py",
        "app/services/pack_upload_service.py",
        "app/schemas/driver_pack.py",
        "app/models/driver_pack.py",
        "app/models/host_pack_feature_status.py",
        "app/models/host_pack_installation.py",
        "app/models/host_runtime_installation.py",
        "app/pack/__init__.py",
        "app/pack/manifest.py",
        "app/pack/adapter.py",
        "app/routers/admin_appium_nodes.py",
        "app/routers/nodes.py",
        "app/models/appium_node.py",
        "app/models/appium_node_resource_claim.py",
        "app/services/appium_capability_keys.py",
        "app/services/appium_node_locking.py",
        "app/services/appium_node_resource_service.py",
        "app/services/appium_reconciler.py",
        "app/services/appium_reconciler_agent.py",
        "app/services/appium_reconciler_allocation.py",
        "app/services/appium_reconciler_convergence.py",
        "app/services/desired_state_writer.py",
        "app/services/heartbeat.py",
        "app/services/heartbeat_outcomes.py",
        "app/services/node_health.py",
        "app/services/node_service_common.py",
        "app/services/node_service_types.py",
        "app/models/device.py",
        "app/models/device_event.py",
        "app/models/device_group.py",
        "app/models/device_intent.py",
        "app/models/device_intent_dirty.py",
        "app/models/device_reservation.py",
        "app/models/device_test_data_audit_log.py",
        "app/routers/bulk.py",
        "app/routers/device_groups.py",
        "app/routers/device_route_helpers.py",
        "app/routers/devices.py",
        "app/routers/devices_control.py",
        "app/routers/devices_core.py",
        "app/routers/devices_test_data.py",
        "app/routers/devices_verification.py",
        "app/routers/lifecycle.py",
        "app/schemas/device.py",
        "app/schemas/device_filters.py",
        "app/schemas/device_group.py",
        "app/schemas/lifecycle.py",
        "app/schemas/maintenance.py",
        "app/schemas/test_data.py",
        "app/services/bulk_service.py",
        "app/services/capability_service.py",
        "app/services/data_cleanup.py",
        "app/services/device_attention.py",
        "app/services/device_connectivity.py",
        "app/services/device_event_service.py",
        "app/services/device_group_service.py",
        "app/services/device_health.py",
        "app/services/device_health_view.py",
        "app/services/device_identity.py",
        "app/services/device_identity_conflicts.py",
        "app/services/device_locking.py",
        "app/services/device_presenter.py",
        "app/services/device_readiness.py",
        "app/services/device_recovery_job.py",
        "app/services/device_service.py",
        "app/services/device_state.py",
        "app/services/device_verification.py",
        "app/services/device_verification_execution.py",
        "app/services/device_verification_job_state.py",
        "app/services/device_verification_preparation.py",
        "app/services/device_verification_runner.py",
        "app/services/device_write.py",
        "app/services/fleet_capacity.py",
        "app/services/intent_evaluator.py",
        "app/services/intent_reconciler.py",
        "app/services/intent_service.py",
        "app/services/intent_types.py",
        "app/services/lifecycle_incident_service.py",
        "app/services/lifecycle_policy.py",
        "app/services/lifecycle_policy_actions.py",
        "app/services/lifecycle_policy_state.py",
        "app/services/lifecycle_policy_summary.py",
        "app/services/lifecycle_state_machine.py",
        "app/services/lifecycle_state_machine_hooks.py",
        "app/services/lifecycle_state_machine_types.py",
        "app/services/maintenance_service.py",
        "app/services/platform_label_service.py",
        "app/services/property_refresh.py",
        "app/services/test_data_service.py",
        "app/models/session.py",
        "app/routers/sessions.py",
        "app/services/session_filters.py",
        "app/services/session_probe_constants.py",
        "app/services/session_service.py",
        "app/services/session_sync.py",
        "app/services/session_viability.py",
        "app/services/session_viability_types.py",
        "app/models/test_run.py",
        "app/routers/runs.py",
        "app/schemas/run.py",
        "app/services/run_reaper.py",
        "app/services/run_reservation_service.py",
        "app/services/run_service.py",
        # Phase 1 — ``app/core/config.py`` carries auth-forwarding
        # properties that import ``app.auth.auth_settings`` at the top
        # of the module. This breaks the "core-purity" rule for the
        # duration of the auth forwarders. Phase 16 deletes the
        # forwarders along with this exemption.
        "app/core/config.py",
    }
)
