from __future__ import annotations

import importlib
from typing import TYPE_CHECKING

import pytest

if TYPE_CHECKING:
    from collections.abc import Iterable


DOMAIN_SUBMODULES: dict[str, tuple[str, ...]] = {
    "analytics": ("config", "models", "router", "schemas", "service"),
    "settings": ("config", "models", "registry", "router", "schemas", "service", "service_config"),
    "webhooks": ("config", "dispatcher", "models", "router", "schemas", "service"),
    "events": ("catalog", "config", "event_bus", "models", "router", "schemas", "schemas_catalog", "service_system"),
    "jobs": ("config", "kinds", "models", "queue", "statuses"),
    "grid": ("config", "router", "schemas", "service"),
    "plugins": ("config", "models", "router", "schemas", "service"),
    "agent_comm": (
        "circuit_breaker",
        "client",
        "config",
        "error_codes",
        "http_pool",
        "models",
        "operations",
        "probe_result",
        "reconfigure_delivery",
        "snapshot",
    ),
    "hosts": (
        "models",
        "router",
        "router_terminal",
        "schemas",
        "service",
        "service_diagnostics",
        "service_hardware_telemetry",
        "service_resource_telemetry",
        "service_terminal_audit",
        "service_terminal_proxy",
        "service_versioning",
    ),
    "packs": (
        "adapter",
        "config",
        "manifest",
        "models",
        "routers",
        "routers.agent_state",
        "routers.authoring",
        "routers.catalog",
        "routers.export",
        "routers.host_features",
        "routers.templates",
        "routers.uploads",
        "schemas",
        "services",
        "services.audit",
        "services.capability",
        "services.delete",
        "services.desired_state",
        "services.discovery",
        "services.drain",
        "services.export",
        "services.feature_dispatch",
        "services.feature_status",
        "services.host_compatibility",
        "services.ingest",
        "services.lifecycle",
        "services.platform_catalog",
        "services.platform_resolver",
        "services.policy",
        "services.release",
        "services.release_ordering",
        "services.service",
        "services.start_shim",
        "services.status",
        "services.storage",
        "services.template",
        "services.upload",
    ),
    "appium_nodes": (
        "exception_handlers",
        "exceptions",
        "models",
        "routers",
        "routers.admin",
        "routers.nodes",
        "services",
        "services.capability_keys",
        "services.common",
        "services.desired_state_writer",
        "services.heartbeat",
        "services.heartbeat_outcomes",
        "services.locking",
        "services.node_health",
        "services.reconciler",
        "services.reconciler_agent",
        "services.reconciler_allocation",
        "services.reconciler_convergence",
        "services.resource_service",
    ),
    "devices": (
        "locking",
        "models",
        "models.device",
        "models.event",
        "models.group",
        "models.intent",
        "models.intent_dirty",
        "models.reservation",
        "models.test_data_audit",
        "routers",
        "routers.bulk",
        "routers.catalog",
        "routers.control",
        "routers.core",
        "routers.groups",
        "routers.helpers",
        "routers.lifecycle_incidents",
        "routers.test_data",
        "routers.verification",
        "schemas",
        "schemas.device",
        "schemas.filters",
        "schemas.group",
        "schemas.lifecycle",
        "schemas.maintenance",
        "schemas.test_data",
        "services",
        "services.attention",
        "services.bulk",
        "services.capability",
        "services.connectivity",
        "services.data_cleanup",
        "services.event",
        "services.fleet_capacity",
        "services.groups",
        "services.health",
        "services.health_view",
        "services.identity",
        "services.identity_conflicts",
        "services.intent",
        "services.intent_evaluator",
        "services.intent_reconciler",
        "services.intent_types",
        "services.lifecycle_incidents",
        "services.lifecycle_policy",
        "services.lifecycle_policy_actions",
        "services.lifecycle_policy_state",
        "services.lifecycle_policy_summary",
        "services.lifecycle_state_machine",
        "services.lifecycle_state_machine_hooks",
        "services.lifecycle_state_machine_types",
        "services.maintenance",
        "services.platform_label",
        "services.presenter",
        "services.property_refresh",
        "services.readiness",
        "services.recovery_job",
        "services.service",
        "services.state",
        "services.test_data",
        "services.verification",
        "services.verification_execution",
        "services.verification_job_state",
        "services.verification_preparation",
        "services.verification_runner",
        "services.write",
    ),
    "sessions": (
        "filters",
        "models",
        "probe_constants",
        "router",
        "service",
        "service_sync",
        "service_viability",
        "viability_types",
    ),
    "runs": (
        "models",
        "router",
        "schemas",
        "service",
        "service_reaper",
        "service_reservation",
    ),
}

SHIM_SENTINELS: dict[str, tuple[str, str, str]] = {
    "app.routers.analytics": ("app.analytics.router", "router", "router"),
    "app.services.analytics_service": ("app.analytics.service", "get_fleet_overview", "get_fleet_overview"),
    "app.schemas.analytics": ("app.analytics.schemas", "FleetOverview", "FleetOverview"),
    "app.models.analytics_capacity_snapshot": (
        "app.analytics.models",
        "AnalyticsCapacitySnapshot",
        "AnalyticsCapacitySnapshot",
    ),
    "app.routers.settings": ("app.settings.router", "router", "router"),
    "app.services.settings_registry": ("app.settings.registry", "SETTINGS_REGISTRY", "SETTINGS_REGISTRY"),
    "app.services.settings_service": ("app.settings.service", "settings_service", "settings_service"),
    "app.services.config_service": ("app.settings.service_config", "get_device_config", "get_device_config"),
    "app.schemas.setting": ("app.settings.schemas", "SettingRead", "SettingRead"),
    "app.models.setting": ("app.settings.models", "Setting", "Setting"),
    "app.models.config_audit_log": ("app.settings.models", "ConfigAuditLog", "ConfigAuditLog"),
    "app.routers.webhooks": ("app.webhooks.router", "router", "router"),
    "app.services.webhook_dispatcher": ("app.webhooks.dispatcher", "configure", "configure"),
    "app.services.webhook_service": ("app.webhooks.service", "list_webhooks", "list_webhooks"),
    "app.schemas.webhook": ("app.webhooks.schemas", "WebhookRead", "WebhookRead"),
    "app.models.webhook": ("app.webhooks.models", "Webhook", "Webhook"),
    "app.models.webhook_delivery": ("app.webhooks.models", "WebhookDelivery", "WebhookDelivery"),
    "app.routers.events": ("app.events.router", "router", "router"),
    "app.services.event_bus": ("app.events.event_bus", "event_bus", "event_bus"),
    "app.services.event_catalog": ("app.events.catalog", "PUBLIC_EVENT_NAMES", "PUBLIC_EVENT_NAMES"),
    "app.services.system_event_service": ("app.events.service_system", "iter_system_events", "iter_system_events"),
    "app.schemas.event": ("app.events.schemas", "SystemEventRead", "SystemEventRead"),
    "app.schemas.event_catalog": ("app.events.schemas_catalog", "EventCatalogRead", "EventCatalogRead"),
    "app.models.system_event": ("app.events.models", "SystemEvent", "SystemEvent"),
    "app.services.job_queue": ("app.jobs.queue", "create_job", "create_job"),
    "app.services.job_kind_constants": (
        "app.jobs.kinds",
        "JOB_KIND_DEVICE_VERIFICATION",
        "JOB_KIND_DEVICE_VERIFICATION",
    ),
    "app.services.job_status_constants": ("app.jobs.statuses", "JOB_STATUS_PENDING", "JOB_STATUS_PENDING"),
    "app.models.job": ("app.jobs.models", "Job", "Job"),
    "app.routers.grid": ("app.grid.router", "router", "router"),
    "app.services.grid_service": ("app.grid.service", "get_grid_status", "get_grid_status"),
    "app.schemas.grid": ("app.grid.schemas", "GridStatusRead", "GridStatusRead"),
    "app.schemas.health": ("app.core.schemas_health", "HealthStatusRead", "HealthStatusRead"),
    "app.routers.plugins": ("app.plugins.router", "router", "router"),
    "app.services.plugin_service": ("app.plugins.service", "list_plugins", "list_plugins"),
    "app.schemas.plugin": ("app.plugins.schemas", "PluginRead", "PluginRead"),
    "app.models.appium_plugin": ("app.plugins.models", "AppiumPlugin", "AppiumPlugin"),
    "app.agent_client": ("app.agent_comm.client", "request", "request"),
    "app.services.agent_http_pool": ("app.agent_comm.http_pool", "agent_http_pool", "agent_http_pool"),
    "app.services.agent_circuit_breaker": (
        "app.agent_comm.circuit_breaker",
        "agent_circuit_breaker",
        "agent_circuit_breaker",
    ),
    "app.services.agent_operations": ("app.agent_comm.operations", "agent_health", "agent_health"),
    "app.services.agent_error_codes": ("app.agent_comm.error_codes", "AgentErrorCode", "AgentErrorCode"),
    "app.services.agent_probe_result": ("app.agent_comm.probe_result", "ProbeResult", "ProbeResult"),
    "app.services.agent_reconfigure_delivery": (
        "app.agent_comm.reconfigure_delivery",
        "deliver_agent_reconfigures",
        "deliver_agent_reconfigures",
    ),
    "app.services.agent_snapshot": ("app.agent_comm.snapshot", "parse_running_nodes", "parse_running_nodes"),
    "app.models.agent_reconfigure_outbox": (
        "app.agent_comm.models",
        "AgentReconfigureOutbox",
        "AgentReconfigureOutbox",
    ),
    "app.schemas.host": ("app.hosts.schemas", "HostRead", "HostRead"),
    "app.models.host": ("app.hosts.models", "Host", "Host"),
    "app.models.host_resource_sample": ("app.hosts.models", "HostResourceSample", "HostResourceSample"),
    "app.models.host_terminal_session": ("app.hosts.models", "HostTerminalSession", "HostTerminalSession"),
    "app.models.host_plugin_runtime_status": (
        "app.hosts.models",
        "HostPluginRuntimeStatus",
        "HostPluginRuntimeStatus",
    ),
    "app.routers.hosts": ("app.hosts.router", "router", "router"),
    "app.routers.host_terminal": ("app.hosts.router_terminal", "router", "router"),
    "app.services.host_service": ("app.hosts.service", "get_host", "get_host"),
    "app.services.host_diagnostics": (
        "app.hosts.service_diagnostics",
        "get_host_diagnostics",
        "get_host_diagnostics",
    ),
    "app.services.host_resource_telemetry": (
        "app.hosts.service_resource_telemetry",
        "host_resource_telemetry_loop",
        "host_resource_telemetry_loop",
    ),
    "app.services.host_terminal_audit": (
        "app.hosts.service_terminal_audit",
        "open_session",
        "open_session",
    ),
    "app.services.host_terminal_proxy": (
        "app.hosts.service_terminal_proxy",
        "proxy_terminal_session",
        "proxy_terminal_session",
    ),
    "app.services.host_versioning": (
        "app.hosts.service_versioning",
        "get_agent_version_status",
        "get_agent_version_status",
    ),
    "app.services.hardware_telemetry": (
        "app.hosts.service_hardware_telemetry",
        "hardware_telemetry_loop",
        "hardware_telemetry_loop",
    ),
    "app.routers.driver_packs": ("app.packs.routers.catalog", "router", "router"),
    "app.routers.driver_pack_authoring": ("app.packs.routers.authoring", "router", "router"),
    "app.routers.driver_pack_export": ("app.packs.routers.export", "router", "router"),
    "app.routers.driver_pack_templates": ("app.packs.routers.templates", "router", "router"),
    "app.routers.driver_pack_uploads": ("app.packs.routers.uploads", "router", "router"),
    "app.routers.agent_driver_packs": ("app.packs.routers.agent_state", "router", "router"),
    "app.routers.host_driver_pack_features": ("app.packs.routers.host_features", "router", "router"),
    "app.services.pack_service": ("app.packs.services.service", "list_catalog", "list_catalog"),
    "app.services.pack_audit_service": ("app.packs.services.audit", "record_pack_upload", "record_pack_upload"),
    "app.services.pack_capability_service": (
        "app.packs.services.capability",
        "render_stereotype",
        "render_stereotype",
    ),
    "app.services.pack_delete_service": ("app.packs.services.delete", "delete_pack", "delete_pack"),
    "app.services.pack_desired_state_service": (
        "app.packs.services.desired_state",
        "compute_desired",
        "compute_desired",
    ),
    "app.services.pack_discovery_service": (
        "app.packs.services.discovery",
        "discover_devices",
        "discover_devices",
    ),
    "app.services.pack_drain": ("app.packs.services.drain", "pack_drain_loop", "pack_drain_loop"),
    "app.services.pack_export_service": ("app.packs.services.export", "export_pack", "export_pack"),
    "app.services.pack_feature_dispatch_service": (
        "app.packs.services.feature_dispatch",
        "dispatch_feature_action",
        "dispatch_feature_action",
    ),
    "app.services.pack_feature_status_service": (
        "app.packs.services.feature_status",
        "record_feature_status",
        "record_feature_status",
    ),
    "app.services.pack_host_compatibility": (
        "app.packs.services.host_compatibility",
        "manifest_supports_host_os",
        "manifest_supports_host_os",
    ),
    "app.services.pack_ingest_service": ("app.packs.services.ingest", "ingest_pack_tarball", "ingest_pack_tarball"),
    "app.services.pack_lifecycle_service": (
        "app.packs.services.lifecycle",
        "transition_pack_state",
        "transition_pack_state",
    ),
    "app.services.pack_platform_catalog": (
        "app.packs.services.platform_catalog",
        "device_is_virtual",
        "device_is_virtual",
    ),
    "app.services.pack_platform_resolver": (
        "app.packs.services.platform_resolver",
        "resolve_pack_platform",
        "resolve_pack_platform",
    ),
    "app.services.pack_policy_service": ("app.packs.services.policy", "set_runtime_policy", "set_runtime_policy"),
    "app.services.pack_release_ordering": (
        "app.packs.services.release_ordering",
        "selected_release",
        "selected_release",
    ),
    "app.services.pack_release_service": ("app.packs.services.release", "list_releases", "list_releases"),
    "app.services.pack_start_shim": (
        "app.packs.services.start_shim",
        "build_pack_start_payload",
        "build_pack_start_payload",
    ),
    "app.services.pack_status_service": ("app.packs.services.status", "apply_status", "apply_status"),
    "app.services.pack_storage_service": (
        "app.packs.services.storage",
        "PackStorageService",
        "PackStorageService",
    ),
    "app.services.pack_template_service": ("app.packs.services.template", "list_templates", "list_templates"),
    "app.services.pack_upload_service": ("app.packs.services.upload", "upload_pack", "upload_pack"),
    "app.schemas.driver_pack": ("app.packs.schemas", "PackOut", "PackOut"),
    "app.models.driver_pack": ("app.packs.models", "DriverPack", "DriverPack"),
    "app.models.host_pack_feature_status": (
        "app.packs.models",
        "HostPackFeatureStatus",
        "HostPackFeatureStatus",
    ),
    "app.models.host_pack_installation": ("app.packs.models", "HostPackInstallation", "HostPackInstallation"),
    "app.models.host_runtime_installation": (
        "app.packs.models",
        "HostRuntimeInstallation",
        "HostRuntimeInstallation",
    ),
    "app.pack.manifest": ("app.packs.manifest", "Manifest", "Manifest"),
    "app.pack.adapter": ("app.packs.adapter", "DriverPackAdapter", "DriverPackAdapter"),
    "app.routers.admin_appium_nodes": ("app.appium_nodes.routers.admin", "router", "router"),
    "app.routers.nodes": ("app.appium_nodes.routers.nodes", "router", "router"),
    "app.models.appium_node": ("app.appium_nodes.models", "AppiumNode", "AppiumNode"),
    "app.models.appium_node_resource_claim": (
        "app.appium_nodes.models",
        "AppiumNodeResourceClaim",
        "AppiumNodeResourceClaim",
    ),
    "app.services.appium_capability_keys": (
        "app.appium_nodes.services.capability_keys",
        "sanitize_appium_caps",
        "sanitize_appium_caps",
    ),
    "app.services.appium_node_locking": (
        "app.appium_nodes.services.locking",
        "lock_appium_node_for_device",
        "lock_appium_node_for_device",
    ),
    "app.services.appium_node_resource_service": (
        "app.appium_nodes.services.resource_service",
        "get_capabilities",
        "get_capabilities",
    ),
    "app.services.appium_reconciler": (
        "app.appium_nodes.services.reconciler",
        "appium_reconciler_loop",
        "appium_reconciler_loop",
    ),
    "app.services.appium_reconciler_agent": (
        "app.appium_nodes.services.reconciler_agent",
        "start_node",
        "start_node",
    ),
    "app.services.appium_reconciler_allocation": (
        "app.appium_nodes.services.reconciler_allocation",
        "candidate_ports",
        "candidate_ports",
    ),
    "app.services.appium_reconciler_convergence": (
        "app.appium_nodes.services.reconciler_convergence",
        "converge_host_rows",
        "converge_host_rows",
    ),
    "app.services.desired_state_writer": (
        "app.appium_nodes.services.desired_state_writer",
        "write_desired_state",
        "write_desired_state",
    ),
    "app.services.heartbeat": ("app.appium_nodes.services.heartbeat", "heartbeat_loop", "heartbeat_loop"),
    "app.services.heartbeat_outcomes": (
        "app.appium_nodes.services.heartbeat_outcomes",
        "HeartbeatOutcome",
        "HeartbeatOutcome",
    ),
    "app.services.node_health": ("app.appium_nodes.services.node_health", "node_health_loop", "node_health_loop"),
    "app.services.node_service_common": (
        "app.appium_nodes.services.common",
        "build_grid_stereotype_caps",
        "build_grid_stereotype_caps",
    ),
    "app.services.node_service_types": (
        "app.appium_nodes.exceptions",
        "NodeManagerError",
        "NodeManagerError",
    ),
    "app.models.device": ("app.devices.models", "Device", "Device"),
    "app.models.device_event": ("app.devices.models", "DeviceEvent", "DeviceEvent"),
    "app.models.device_group": ("app.devices.models", "DeviceGroup", "DeviceGroup"),
    "app.models.device_intent": ("app.devices.models", "DeviceIntent", "DeviceIntent"),
    "app.models.device_intent_dirty": ("app.devices.models", "DeviceIntentDirty", "DeviceIntentDirty"),
    "app.models.device_reservation": ("app.devices.models", "DeviceReservation", "DeviceReservation"),
    "app.models.device_test_data_audit_log": (
        "app.devices.models",
        "DeviceTestDataAuditLog",
        "DeviceTestDataAuditLog",
    ),
    "app.routers.bulk": ("app.devices.routers.bulk", "router", "router"),
    "app.routers.device_groups": ("app.devices.routers.groups", "router", "router"),
    "app.routers.device_route_helpers": ("app.devices.routers.helpers", "get_device_or_404", "get_device_or_404"),
    "app.routers.devices": ("app.devices.routers.catalog", "router", "router"),
    "app.routers.devices_control": ("app.devices.routers.control", "router", "router"),
    "app.routers.devices_core": ("app.devices.routers.core", "router", "router"),
    "app.routers.devices_test_data": ("app.devices.routers.test_data", "router", "router"),
    "app.routers.devices_verification": ("app.devices.routers.verification", "router", "router"),
    "app.routers.lifecycle": ("app.devices.routers.lifecycle_incidents", "router", "router"),
    "app.schemas.device": ("app.devices.schemas.device", "DeviceRead", "DeviceRead"),
    "app.schemas.device_filters": ("app.devices.schemas.filters", "DeviceQueryFilters", "DeviceQueryFilters"),
    "app.schemas.device_group": ("app.devices.schemas.group", "DeviceGroupRead", "DeviceGroupRead"),
    "app.schemas.lifecycle": ("app.devices.schemas.lifecycle", "LifecycleIncidentRead", "LifecycleIncidentRead"),
    "app.schemas.maintenance": (
        "app.devices.schemas.maintenance",
        "DeviceMaintenanceUpdate",
        "DeviceMaintenanceUpdate",
    ),
    "app.schemas.test_data": ("app.devices.schemas.test_data", "TestDataRead", "TestDataRead"),
    "app.services.bulk_service": ("app.devices.services.bulk", "bulk_start_nodes", "bulk_start_nodes"),
    "app.services.capability_service": (
        "app.devices.services.capability",
        "get_device_capabilities",
        "get_device_capabilities",
    ),
    "app.services.data_cleanup": ("app.devices.services.data_cleanup", "data_cleanup_loop", "data_cleanup_loop"),
    "app.services.device_attention": (
        "app.devices.services.attention",
        "compute_needs_attention",
        "compute_needs_attention",
    ),
    "app.services.device_connectivity": (
        "app.devices.services.connectivity",
        "device_connectivity_loop",
        "device_connectivity_loop",
    ),
    "app.services.device_event_service": ("app.devices.services.event", "record_event", "record_event"),
    "app.services.device_group_service": ("app.devices.services.groups", "create_group", "create_group"),
    "app.services.device_health": (
        "app.devices.services.health",
        "apply_node_state_transition",
        "apply_node_state_transition",
    ),
    "app.services.device_health_view": (
        "app.devices.services.health_view",
        "build_public_summary",
        "build_public_summary",
    ),
    "app.services.device_identity": (
        "app.devices.services.identity",
        "appium_connection_target",
        "appium_connection_target",
    ),
    "app.services.device_identity_conflicts": (
        "app.devices.services.identity_conflicts",
        "DeviceIdentityConflictError",
        "DeviceIdentityConflictError",
    ),
    "app.services.device_locking": ("app.devices.locking", "lock_device", "lock_device"),
    "app.services.device_presenter": ("app.devices.services.presenter", "serialize_device", "serialize_device"),
    "app.services.device_readiness": (
        "app.devices.services.readiness",
        "is_ready_for_use_async",
        "is_ready_for_use_async",
    ),
    "app.services.device_recovery_job": (
        "app.devices.services.recovery_job",
        "run_device_recovery_job",
        "run_device_recovery_job",
    ),
    "app.services.device_service": ("app.devices.services.service", "get_device", "get_device"),
    "app.services.device_state": ("app.devices.services.state", "set_operational_state", "set_operational_state"),
    "app.services.device_verification": (
        "app.devices.services.verification",
        "start_verification_job",
        "start_verification_job",
    ),
    "app.services.device_verification_execution": (
        "app.devices.services.verification_execution",
        "run_device_health",
        "run_device_health",
    ),
    "app.services.device_verification_job_state": (
        "app.devices.services.verification_job_state",
        "public_snapshot",
        "public_snapshot",
    ),
    "app.services.device_verification_preparation": (
        "app.devices.services.verification_preparation",
        "validate_create_request",
        "validate_create_request",
    ),
    "app.services.device_verification_runner": (
        "app.devices.services.verification_runner",
        "run_persisted_verification_job",
        "run_persisted_verification_job",
    ),
    "app.services.device_write": ("app.devices.services.write", "apply_device_payload", "apply_device_payload"),
    "app.services.fleet_capacity": (
        "app.devices.services.fleet_capacity",
        "get_fleet_capacity_timeline",
        "get_fleet_capacity_timeline",
    ),
    "app.services.intent_evaluator": (
        "app.devices.services.intent_evaluator",
        "evaluate_node_process",
        "evaluate_node_process",
    ),
    "app.services.intent_reconciler": (
        "app.devices.services.intent_reconciler",
        "device_intent_reconciler_loop",
        "device_intent_reconciler_loop",
    ),
    "app.services.intent_service": (
        "app.devices.services.intent",
        "register_intents_and_reconcile",
        "register_intents_and_reconcile",
    ),
    "app.services.intent_types": ("app.devices.services.intent_types", "IntentRegistration", "IntentRegistration"),
    "app.services.lifecycle_incident_service": (
        "app.devices.services.lifecycle_incidents",
        "serialize_lifecycle_incident",
        "serialize_lifecycle_incident",
    ),
    "app.services.lifecycle_policy": (
        "app.devices.services.lifecycle_policy",
        "handle_health_failure",
        "handle_health_failure",
    ),
    "app.services.lifecycle_policy_actions": (
        "app.devices.services.lifecycle_policy_actions",
        "handle_node_crash",
        "handle_node_crash",
    ),
    "app.services.lifecycle_policy_state": (
        "app.devices.services.lifecycle_policy_state",
        "default_state",
        "default_state",
    ),
    "app.services.lifecycle_policy_summary": (
        "app.devices.services.lifecycle_policy_summary",
        "build_lifecycle_policy",
        "build_lifecycle_policy",
    ),
    "app.services.lifecycle_state_machine": (
        "app.devices.services.lifecycle_state_machine",
        "DeviceStateMachine",
        "DeviceStateMachine",
    ),
    "app.services.lifecycle_state_machine_hooks": (
        "app.devices.services.lifecycle_state_machine_hooks",
        "EventLogHook",
        "EventLogHook",
    ),
    "app.services.lifecycle_state_machine_types": (
        "app.devices.services.lifecycle_state_machine_types",
        "TransitionEvent",
        "TransitionEvent",
    ),
    "app.services.maintenance_service": ("app.devices.services.maintenance", "enter_maintenance", "enter_maintenance"),
    "app.services.platform_label_service": (
        "app.devices.services.platform_label",
        "load_platform_label",
        "load_platform_label",
    ),
    "app.services.property_refresh": (
        "app.devices.services.property_refresh",
        "property_refresh_loop",
        "property_refresh_loop",
    ),
    "app.services.test_data_service": (
        "app.devices.services.test_data",
        "get_device_test_data",
        "get_device_test_data",
    ),
    "app.models.session": ("app.sessions.models", "Session", "Session"),
    "app.routers.sessions": ("app.sessions.router", "router", "router"),
    "app.services.session_filters": (
        "app.sessions.filters",
        "exclude_non_test_sessions",
        "exclude_non_test_sessions",
    ),
    "app.services.session_probe_constants": ("app.sessions.probe_constants", "PROBE_TEST_NAME", "PROBE_TEST_NAME"),
    "app.services.session_service": ("app.sessions.service", "get_session", "get_session"),
    "app.services.session_sync": ("app.sessions.service_sync", "session_sync_loop", "session_sync_loop"),
    "app.services.session_viability": (
        "app.sessions.service_viability",
        "run_session_viability_probe",
        "run_session_viability_probe",
    ),
    "app.services.session_viability_types": (
        "app.sessions.viability_types",
        "SessionViabilityCheckedBy",
        "SessionViabilityCheckedBy",
    ),
    "app.models.test_run": ("app.runs.models", "TestRun", "TestRun"),
    "app.routers.runs": ("app.runs.router", "router", "router"),
    "app.schemas.run": ("app.runs.schemas", "RunCreate", "RunCreate"),
    "app.services.run_reaper": ("app.runs.service_reaper", "run_reaper_loop", "run_reaper_loop"),
    "app.services.run_reservation_service": (
        "app.runs.service_reservation",
        "get_device_reservation_with_entry",
        "get_device_reservation_with_entry",
    ),
    "app.services.run_service": ("app.runs.service", "create_run", "create_run"),
}


@pytest.mark.parametrize(("domain", "submodules"), DOMAIN_SUBMODULES.items())
def test_domain_submodules_import(domain: str, submodules: Iterable[str]) -> None:
    package = importlib.import_module(f"app.{domain}")
    assert package is not None
    for submodule in submodules:
        assert importlib.import_module(f"app.{domain}.{submodule}") is not None


@pytest.mark.parametrize(
    ("shim_name", "target_name", "shim_attr", "target_attr"),
    [(shim_name, *target) for shim_name, target in SHIM_SENTINELS.items()],
)
def test_legacy_shims_reexport_domain_objects(
    shim_name: str,
    target_name: str,
    shim_attr: str,
    target_attr: str,
) -> None:
    shim = importlib.import_module(shim_name)
    target = importlib.import_module(target_name)
    assert getattr(shim, shim_attr) is getattr(target, target_attr)
