"""Pure unit tests for state_write_guard._resolve_caller_name.

These tests do not exercise real SQLAlchemy dispatch. They pin the
prefix-match and None-skip semantics of the resolver so SA-internals
drift surfaces here before the wider integration suite fails.
"""

from __future__ import annotations

from app.devices.services.state_write_guard import _resolve_caller_name


def test_returns_unknown_when_iterator_is_empty() -> None:
    assert _resolve_caller_name(iter([])) == "<unknown>"


def test_returns_unknown_when_only_sqlalchemy_frames() -> None:
    names = ["sqlalchemy.orm.attributes", "sqlalchemy.orm.events"]
    assert _resolve_caller_name(iter(names)) == "<unknown>"


def test_skips_sqlalchemy_prefix_and_returns_first_application_name() -> None:
    names = ["sqlalchemy.orm.attributes", "app.devices.services.state"]
    assert _resolve_caller_name(iter(names)) == "app.devices.services.state"


def test_skips_none_entries_representing_exec_string_frames() -> None:
    # ``inspect.getmodule(frame)`` returns ``None`` for frames whose code object
    # was generated by ``exec`` with filename "<string>" (e.g. SQLAlchemy's
    # declarative ``_declarative_constructor``). Resolver must skip them.
    names = [None, "app.devices.services.write"]
    assert _resolve_caller_name(iter(names)) == "app.devices.services.write"


def test_mixed_sa_and_exec_frames_then_real_caller() -> None:
    names = [
        "sqlalchemy.orm.attributes",
        None,
        "sqlalchemy.orm.attributes",
        None,
        "app.devices.services.lifecycle_state_machine",
    ]
    assert _resolve_caller_name(iter(names)) == "app.devices.services.lifecycle_state_machine"


def test_prefix_match_is_permissive_documents_current_contract() -> None:
    # The match is ``str.startswith("sqlalchemy")`` — anything beginning with
    # the literal "sqlalchemy" is skipped, including hypothetical packages
    # like "sqlalchemyplus". If this changes to a stricter "sqlalchemy."
    # match, flip this assertion and update the docs.
    assert _resolve_caller_name(iter(["sqlalchemyplus.foo"])) == "<unknown>"


def test_match_is_anchored_at_start_of_name() -> None:
    # Names where "sqlalchemy" appears anywhere except position 0 are not
    # treated as internals.
    assert _resolve_caller_name(iter(["foo.sqlalchemy.bar"])) == "foo.sqlalchemy.bar"


def test_empty_string_name_is_returned_documents_inspect_getmodule_contract() -> None:
    # inspect.getmodule() never returns a Module with __name__ == "" for real
    # frames (exec-generated frames produce None, not an empty-name module).
    # The resolver therefore does not need a separate empty-string guard; this
    # test documents that contract. If inspect.getmodule() semantics ever change,
    # this will surface as a behavior shift here before the wider suite breaks.
    assert _resolve_caller_name(iter([""])) == ""
