from __future__ import annotations

import importlib
from typing import TYPE_CHECKING

import pytest

if TYPE_CHECKING:
    from collections.abc import Iterable


DOMAIN_SUBMODULES: dict[str, tuple[str, ...]] = {
    "analytics": ("config", "models", "router", "schemas", "service"),
    "settings": ("config", "models", "registry", "router", "schemas", "service", "service_config"),
    "webhooks": ("config", "dispatcher", "models", "router", "schemas", "service"),
    "events": ("catalog", "config", "event_bus", "models", "router", "schemas", "schemas_catalog", "service_system"),
    "jobs": ("config", "kinds", "models", "queue", "statuses"),
    "grid": ("config", "router", "schemas", "service"),
    "plugins": ("config", "models", "router", "schemas", "service"),
    "agent_comm": (
        "circuit_breaker",
        "client",
        "config",
        "error_codes",
        "http_pool",
        "models",
        "operations",
        "probe_result",
        "reconfigure_delivery",
        "snapshot",
    ),
    "hosts": (
        "models",
        "router",
        "router_terminal",
        "schemas",
        "service",
        "service_diagnostics",
        "service_hardware_telemetry",
        "service_resource_telemetry",
        "service_terminal_audit",
        "service_terminal_proxy",
        "service_versioning",
    ),
    "packs": (
        "adapter",
        "config",
        "manifest",
        "models",
        "routers",
        "routers.agent_state",
        "routers.authoring",
        "routers.catalog",
        "routers.export",
        "routers.host_features",
        "routers.templates",
        "routers.uploads",
        "schemas",
        "services",
        "services.audit",
        "services.capability",
        "services.delete",
        "services.desired_state",
        "services.discovery",
        "services.drain",
        "services.export",
        "services.feature_dispatch",
        "services.feature_status",
        "services.host_compatibility",
        "services.ingest",
        "services.lifecycle",
        "services.platform_catalog",
        "services.platform_resolver",
        "services.policy",
        "services.release",
        "services.release_ordering",
        "services.service",
        "services.start_shim",
        "services.status",
        "services.storage",
        "services.template",
        "services.upload",
    ),
    "appium_nodes": (
        "exception_handlers",
        "exceptions",
        "models",
        "routers",
        "routers.admin",
        "routers.nodes",
        "services",
        "services.capability_keys",
        "services.common",
        "services.desired_state_writer",
        "services.heartbeat",
        "services.heartbeat_outcomes",
        "services.locking",
        "services.node_health",
        "services.reconciler",
        "services.reconciler_agent",
        "services.reconciler_allocation",
        "services.reconciler_convergence",
        "services.resource_service",
    ),
    "devices": (
        "locking",
        "models",
        "models.device",
        "models.event",
        "models.group",
        "models.intent",
        "models.intent_dirty",
        "models.reservation",
        "models.test_data_audit",
        "routers",
        "routers.bulk",
        "routers.catalog",
        "routers.control",
        "routers.core",
        "routers.groups",
        "routers.helpers",
        "routers.lifecycle_incidents",
        "routers.test_data",
        "routers.verification",
        "schemas",
        "schemas.device",
        "schemas.filters",
        "schemas.group",
        "schemas.lifecycle",
        "schemas.maintenance",
        "schemas.test_data",
        "services",
        "services.attention",
        "services.bulk",
        "services.capability",
        "services.connectivity",
        "services.data_cleanup",
        "services.event",
        "services.fleet_capacity",
        "services.groups",
        "services.health",
        "services.health_view",
        "services.identity",
        "services.identity_conflicts",
        "services.intent",
        "services.intent_evaluator",
        "services.intent_reconciler",
        "services.intent_types",
        "services.lifecycle_incidents",
        "services.lifecycle_policy",
        "services.lifecycle_policy_actions",
        "services.lifecycle_policy_state",
        "services.lifecycle_policy_summary",
        "services.lifecycle_state_machine",
        "services.lifecycle_state_machine_hooks",
        "services.lifecycle_state_machine_types",
        "services.maintenance",
        "services.platform_label",
        "services.presenter",
        "services.property_refresh",
        "services.readiness",
        "services.recovery_job",
        "services.service",
        "services.state",
        "services.test_data",
        "services.verification",
        "services.verification_execution",
        "services.verification_job_state",
        "services.verification_preparation",
        "services.verification_runner",
        "services.write",
    ),
    "sessions": (
        "filters",
        "models",
        "probe_constants",
        "router",
        "service",
        "service_sync",
        "service_viability",
        "viability_types",
    ),
    "runs": (
        "models",
        "router",
        "schemas",
        "service",
        "service_reaper",
        "service_reservation",
    ),
}


@pytest.mark.parametrize(("domain", "submodules"), DOMAIN_SUBMODULES.items())
def test_domain_submodules_import(domain: str, submodules: Iterable[str]) -> None:
    package = importlib.import_module(f"app.{domain}")
    assert package is not None
    for submodule in submodules:
        assert importlib.import_module(f"app.{domain}.{submodule}") is not None
