"""drop write-only available_capacity_slots column

Revision ID: 86856afd09bb
Revises: a1c3e5f70d92
Create Date: 2026-06-26 16:51:31.347149

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "86856afd09bb"
down_revision: str | None = "a1c3e5f70d92"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analytics_capacity_snapshots", "available_capacity_slots")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analytics_capacity_snapshots",
        sa.Column("available_capacity_slots", sa.INTEGER(), autoincrement=False, nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###
