"""drop host_agent_log_entry

Revision ID: 54d7ea8b93a1
Revises: f1a2b3c4d5e6
Create Date: 2026-06-25 22:02:57.927562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54d7ea8b93a1'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_log_host_ts'), table_name='host_agent_log_entry')
    op.drop_index(op.f('ix_agent_log_received_at'), table_name='host_agent_log_entry')
    op.drop_table('host_agent_log_entry')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host_agent_log_entry',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('host_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('boot_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sequence_no', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('level', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('logger_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], name=op.f('host_agent_log_entry_host_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('host_agent_log_entry_pkey')),
    sa.UniqueConstraint('host_id', 'boot_id', 'sequence_no', name=op.f('uq_agent_log_seq'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_agent_log_received_at'), 'host_agent_log_entry', ['received_at'], unique=False)
    op.create_index(op.f('ix_agent_log_host_ts'), 'host_agent_log_entry', ['host_id', 'ts'], unique=False)
    # ### end Alembic commands ###
