"""add device os version display

Revision ID: 25d460b8cdc5
Revises: d862f008ec14
Create Date: 2026-05-16 01:37:49.999691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25d460b8cdc5'
down_revision: Union[str, None] = 'd862f008ec14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('os_version_display', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'os_version_display')
    # ### end Alembic commands ###
