"""add device_remediation_log

Revision ID: 225a29d636e0
Revises: 2026_07_12_deferred_stop
Create Date: 2026-07-12 16:30:55.817068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '225a29d636e0'
down_revision: Union[str, None] = '2026_07_12_deferred_stop'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_remediation_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('backoff_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('attempt', 'failure', 'reset', 'action')", name=op.f('device_remediation_log_ck_device_remediation_log_kind_check')),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('device_remediation_log_device_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('device_remediation_log_pkey'))
    )
    op.create_index('ix_device_remediation_log_at', 'device_remediation_log', ['at'], unique=False)
    op.create_index('ix_device_remediation_log_device_id_at', 'device_remediation_log', ['device_id', 'at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_device_remediation_log_device_id_at', table_name='device_remediation_log')
    op.drop_index('ix_device_remediation_log_at', table_name='device_remediation_log')
    op.drop_table('device_remediation_log')
    # ### end Alembic commands ###
