"""drop agent_reconfigure_outbox

Revision ID: 49e8065414a1
Revises: a1c7f3e9b2d4
Create Date: 2026-07-08 17:05:20.305082

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49e8065414a1"
down_revision: str | None = "a1c7f3e9b2d4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_reconfigure_outbox_undelivered"), table_name="agent_reconfigure_outbox")
    op.drop_table("agent_reconfigure_outbox")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_reconfigure_outbox",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("device_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("port", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("accepting_new_sessions", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("stop_pending", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("grid_run_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("reconciled_generation", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("delivered_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("delivery_attempts", sa.INTEGER(), server_default=sa.text("0"), autoincrement=False, nullable=False),
        sa.Column("abandoned_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("abandoned_reason", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("agent_reconfigure_outbox_device_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("agent_reconfigure_outbox_pkey")),
    )
    op.create_index(
        op.f("ix_agent_reconfigure_outbox_undelivered"),
        "agent_reconfigure_outbox",
        ["device_id", "delivered_at"],
        unique=False,
    )
    # ### end Alembic commands ###
