"""add host tool_env

Revision ID: cb1b96fae8a0
Revises: 589fdc334be4
Create Date: 2026-05-24 10:51:29.899438

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb1b96fae8a0"
down_revision: str | None = "589fdc334be4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hosts", sa.Column("tool_env", postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hosts", "tool_env")
    # ### end Alembic commands ###
