"""add host_agent_log_entry

Revision ID: d862f008ec14
Revises: e827486cd633
Create Date: 2026-05-15 20:34:47.463839

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d862f008ec14"
down_revision: str | None = "e827486cd633"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "host_agent_log_entry",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("host_id", sa.UUID(), nullable=False),
        sa.Column("boot_id", sa.UUID(), nullable=False),
        sa.Column("sequence_no", sa.BigInteger(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("logger_name", sa.String(length=255), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["host_id"], ["hosts.id"], name=op.f("host_agent_log_entry_host_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("host_agent_log_entry_pkey")),
        sa.UniqueConstraint("host_id", "boot_id", "sequence_no", name="uq_agent_log_seq"),
    )
    op.create_index(op.f("host_agent_log_entry_host_id_idx"), "host_agent_log_entry", ["host_id"], unique=False)
    op.create_index("ix_agent_log_host_ts", "host_agent_log_entry", ["host_id", "ts"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_agent_log_host_ts", table_name="host_agent_log_entry")
    op.drop_index(op.f("host_agent_log_entry_host_id_idx"), table_name="host_agent_log_entry")
    op.drop_table("host_agent_log_entry")
    # ### end Alembic commands ###
