"""drop template fork columns

Revision ID: f1de2fce530c
Revises: cb1b96fae8a0
Create Date: 2026-05-25 15:23:17.475467

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1de2fce530c"
down_revision: str | None = "cb1b96fae8a0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("driver_pack_releases", "derived_from_pack_id")
    op.drop_column("driver_pack_releases", "derived_from_release")
    op.drop_column("driver_pack_releases", "template_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("driver_pack_releases", sa.Column("template_id", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column(
        "driver_pack_releases", sa.Column("derived_from_release", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "driver_pack_releases", sa.Column("derived_from_pack_id", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
