"""baseline postgresql 18 schema

Revision ID: 53063d67b14c
Revises:
Create Date: 2026-05-13 21:01:11.251127

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "53063d67b14c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.create_table(
        "analytics_capacity_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_capacity_slots", sa.Integer(), nullable=False),
        sa.Column("active_sessions", sa.Integer(), nullable=False),
        sa.Column("queued_requests", sa.Integer(), nullable=False),
        sa.Column("available_capacity_slots", sa.Integer(), nullable=False),
        sa.Column("hosts_total", sa.Integer(), server_default="0", nullable=False),
        sa.Column("hosts_online", sa.Integer(), server_default="0", nullable=False),
        sa.Column("devices_total", sa.Integer(), server_default="0", nullable=False),
        sa.Column("devices_available", sa.Integer(), server_default="0", nullable=False),
        sa.Column("devices_offline", sa.Integer(), server_default="0", nullable=False),
        sa.Column("devices_maintenance", sa.Integer(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_analytics_capacity_snapshots_captured_at", "analytics_capacity_snapshots", ["captured_at"], unique=False
    )
    op.create_table(
        "appium_plugins",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("package", sa.String(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("notes", sa.String(), server_default="", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_appium_plugins_name"), "appium_plugins", ["name"], unique=True)
    op.create_table(
        "control_plane_leader_heartbeats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("holder_id", sa.UUID(), nullable=False),
        sa.Column("lock_backend_pid", sa.Integer(), nullable=True),
        sa.Column("acquired_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "control_plane_state_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("namespace", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("namespace", "key", name="uq_control_plane_state_entries_namespace_key"),
    )
    op.create_index(op.f("ix_control_plane_state_entries_key"), "control_plane_state_entries", ["key"], unique=False)
    op.create_index(
        op.f("ix_control_plane_state_entries_namespace"), "control_plane_state_entries", ["namespace"], unique=False
    )
    op.create_table(
        "device_groups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("group_type", sa.Enum("static", "dynamic", name="grouptype"), nullable=False),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index("ix_device_groups_filters_gin", "device_groups", ["filters"], unique=False, postgresql_using="gin")
    op.create_table(
        "driver_packs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("origin", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("maintainer", sa.String(), server_default="", nullable=False),
        sa.Column("license", sa.String(), server_default="", nullable=False),
        sa.Column("current_release", sa.String(), nullable=True),
        sa.Column(
            "state",
            sa.Enum("draft", "enabled", "draining", "disabled", name="packstate", native_enum=False),
            server_default="enabled",
            nullable=False,
        ),
        sa.Column(
            "runtime_policy",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{"strategy": "recommended"}',
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("origin = 'uploaded'", name="driver_packs_origin_ck"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hosts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("hostname", sa.String(), nullable=False),
        sa.Column("ip", sa.String(), nullable=False),
        sa.Column("os_type", sa.Enum("linux", "macos", name="ostype"), nullable=False),
        sa.Column("agent_port", sa.Integer(), nullable=False),
        sa.Column("status", sa.Enum("online", "offline", "pending", name="hoststatus"), nullable=False),
        sa.Column("last_heartbeat", sa.DateTime(timezone=True), nullable=True),
        sa.Column("agent_version", sa.String(), nullable=True),
        sa.Column("capabilities", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hosts_hostname"), "hosts", ["hostname"], unique=True)
    op.create_table(
        "jobs",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("snapshot", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="1", nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jobs_kind"), "jobs", ["kind"], unique=False)
    op.create_index("ix_jobs_kind_status_scheduled_at", "jobs", ["kind", "status", "scheduled_at"], unique=False)
    op.create_index(op.f("ix_jobs_scheduled_at"), "jobs", ["scheduled_at"], unique=False)
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_table(
        "settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_settings_key"), "settings", ["key"], unique=True)
    op.create_table(
        "system_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.String(), server_default=sa.text("(uuidv7())::text"), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_system_events_event_id"), "system_events", ["event_id"], unique=True)
    op.create_index("ix_system_events_data_gin", "system_events", ["data"], unique=False, postgresql_using="gin")
    op.create_index(op.f("ix_system_events_type"), "system_events", ["type"], unique=False)
    op.create_index("ix_system_events_type_created_at", "system_events", ["type", "created_at"], unique=False)
    op.create_table(
        "test_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "pending",
                "preparing",
                "active",
                "completing",
                "completed",
                "failed",
                "expired",
                "cancelled",
                name="runstate",
            ),
            nullable=False,
        ),
        sa.Column("requirements", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("ttl_minutes", sa.Integer(), nullable=False),
        sa.Column("last_heartbeat", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_timeout_sec", sa.Integer(), nullable=False),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "webhooks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("event_types", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "devices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("pack_id", sa.String(), nullable=False),
        sa.Column("platform_id", sa.String(), nullable=False),
        sa.Column("identity_scheme", sa.String(), nullable=False),
        sa.Column("identity_scope", sa.String(), nullable=False),
        sa.Column("identity_value", sa.String(), nullable=False),
        sa.Column("connection_target", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("os_version", sa.String(), nullable=False),
        sa.Column("host_id", sa.UUID(), nullable=False),
        sa.Column(
            "operational_state",
            sa.Enum("available", "busy", "offline", "verifying", name="deviceoperationalstate"),
            nullable=False,
        ),
        sa.Column("hold", sa.Enum("maintenance", "reserved", name="devicehold"), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("manufacturer", sa.String(), nullable=True),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("model_number", sa.String(), nullable=True),
        sa.Column("software_versions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("auto_manage", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("device_type", sa.Enum("real_device", "emulator", "simulator", name="devicetype"), nullable=False),
        sa.Column("connection_type", sa.Enum("usb", "network", "virtual", name="connectiontype"), nullable=False),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("battery_level_percent", sa.Integer(), nullable=True),
        sa.Column("battery_temperature_c", sa.Float(), nullable=True),
        sa.Column(
            "charging_state",
            sa.Enum("charging", "discharging", "full", "not_charging", "unknown", name="hardwarechargingstate"),
            nullable=True,
        ),
        sa.Column(
            "hardware_health_status",
            sa.Enum("unknown", "healthy", "warning", "critical", name="hardwarehealthstatus"),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column(
            "hardware_telemetry_support_status",
            sa.Enum("unknown", "supported", "unsupported", name="hardwaretelemetrysupportstatus"),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column("hardware_telemetry_reported_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("device_config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("test_data", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column(
            "lifecycle_policy_state", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True
        ),
        sa.Column("device_checks_healthy", sa.Boolean(), nullable=True),
        sa.Column("device_checks_summary", sa.Text(), nullable=True),
        sa.Column("device_checks_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("session_viability_status", sa.String(length=16), nullable=True),
        sa.Column("session_viability_error", sa.Text(), nullable=True),
        sa.Column("session_viability_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recovery_allowed", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("recovery_blocked_reason", sa.Text(), nullable=True),
        sa.Column("emulator_state", sa.String(length=32), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["host_id"], ["hosts.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_devices_identity_value"), "devices", ["identity_value"], unique=False)
    op.create_index("ix_devices_device_config_gin", "devices", ["device_config"], unique=False, postgresql_using="gin")
    op.create_index("ix_devices_pack_platform", "devices", ["pack_id", "platform_id"], unique=False)
    op.create_index(
        "ix_devices_search_vector_gin",
        "devices",
        [
            sa.text(
                "to_tsvector('simple'::regconfig, (((((((((((((((COALESCE(name, ''::character varying)::text || "
                "' '::text) || COALESCE(identity_value, ''::character varying)::text) || ' '::text) || "
                "COALESCE(connection_target, ''::character varying)::text) || ' '::text) || "
                "COALESCE(manufacturer, ''::character varying)::text) || ' '::text) || "
                "COALESCE(model, ''::character varying)::text) || ' '::text) || "
                "COALESCE(model_number, ''::character varying)::text) || ' '::text) || "
                "COALESCE(os_version, ''::character varying)::text) || ' '::text) || "
                "COALESCE(pack_id, ''::character varying)::text) || ' '::text) || "
                "COALESCE(platform_id, ''::character varying)::text)"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index("ix_devices_tags_gin", "devices", ["tags"], unique=False, postgresql_using="gin")
    op.create_index("ix_devices_test_data_gin", "devices", ["test_data"], unique=False, postgresql_using="gin")
    op.create_index(
        "uq_devices_host_identity_scheme_value",
        "devices",
        ["host_id", "identity_scheme", "identity_value"],
        unique=True,
        postgresql_where=sa.text("identity_scope = 'host'"),
    )
    op.create_index(
        "uq_devices_identity_scheme_value_global",
        "devices",
        ["identity_scheme", "identity_value"],
        unique=True,
        postgresql_where=sa.text("identity_scope = 'global'"),
    )
    op.create_table(
        "driver_pack_releases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("pack_id", sa.String(), nullable=False),
        sa.Column("release", sa.String(), nullable=False),
        sa.Column("manifest_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("artifact_path", sa.String(), nullable=True),
        sa.Column("artifact_sha256", sa.String(), nullable=True),
        sa.Column("derived_from_pack_id", sa.String(), nullable=True),
        sa.Column("derived_from_release", sa.String(), nullable=True),
        sa.Column("template_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["pack_id"], ["driver_packs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pack_id", "release", name="driver_pack_releases_pack_release_uq"),
    )
    op.create_table(
        "host_pack_doctor_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("host_id", sa.UUID(), nullable=False),
        sa.Column("pack_id", sa.String(), nullable=False),
        sa.Column("check_id", sa.String(), nullable=False),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("message", sa.String(), server_default="", nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["host_id"], ["hosts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["pack_id"], ["driver_packs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("host_id", "pack_id", "check_id", name="host_pack_doctor_results_uq"),
    )
    op.create_table(
        "host_pack_feature_status",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("host_id", sa.UUID(), nullable=False),
        sa.Column("pack_id", sa.String(), nullable=False),
        sa.Column("feature_id", sa.String(), nullable=False),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("detail", sa.String(), server_default="", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["host_id"], ["hosts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("host_id", "pack_id", "feature_id", name="host_pack_feature_status_uq"),
    )
    op.create_index(op.f("ix_host_pack_feature_status_host_id"), "host_pack_feature_status", ["host_id"], unique=False)
    op.create_table(
        "host_pack_installations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("host_id", sa.UUID(), nullable=False),
        sa.Column("pack_id", sa.String(), nullable=False),
        sa.Column("pack_release", sa.String(), nullable=False),
        sa.Column("runtime_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), server_default="pending", nullable=False),
        sa.Column("resolved_install_spec", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("artifact_sha256", sa.String(), nullable=True),
        sa.Column("installed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("installer_log_excerpt", sa.String(), nullable=True),
        sa.Column("resolver_version", sa.String(), nullable=True),
        sa.Column("blocked_reason", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["host_id"], ["hosts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["pack_id"], ["driver_packs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("host_id", "pack_id", name="host_pack_installations_host_pack_uq"),
    )
    op.create_table(
        "host_plugin_runtime_statuses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("host_id", sa.UUID(), nullable=False),
        sa.Column("runtime_id", sa.String(), nullable=False),
        sa.Column("plugin_name", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("blocked_reason", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["host_id"], ["hosts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("host_id", "runtime_id", "plugin_name", name="host_plugin_runtime_statuses_uq"),
    )
    op.create_table(
        "host_resource_samples",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("host_id", sa.UUID(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cpu_percent", sa.Float(), nullable=True),
        sa.Column("memory_used_mb", sa.Integer(), nullable=True),
        sa.Column("memory_total_mb", sa.Integer(), nullable=True),
        sa.Column("disk_used_gb", sa.Float(), nullable=True),
        sa.Column("disk_total_gb", sa.Float(), nullable=True),
        sa.Column("disk_percent", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["host_id"], ["hosts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_host_resource_samples_host_id_recorded_at",
        "host_resource_samples",
        ["host_id", "recorded_at"],
        unique=False,
    )
    op.create_index("ix_host_resource_samples_recorded_at", "host_resource_samples", ["recorded_at"], unique=False)
    op.create_table(
        "host_runtime_installations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("host_id", sa.UUID(), nullable=False),
        sa.Column("runtime_id", sa.String(), nullable=False),
        sa.Column("appium_server_package", sa.String(), nullable=False),
        sa.Column("appium_server_version", sa.String(), nullable=False),
        sa.Column("driver_specs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "plugin_specs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("appium_home", sa.String(), nullable=True),
        sa.Column("refcount", sa.Integer(), server_default="0", nullable=False),
        sa.Column("status", sa.String(), server_default="pending", nullable=False),
        sa.Column("blocked_reason", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["host_id"], ["hosts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("host_id", "runtime_id", name="host_runtime_installations_host_runtime_uq"),
    )
    op.create_table(
        "host_terminal_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("host_id", sa.UUID(), nullable=False),
        sa.Column("opened_by", sa.String(), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("close_reason", sa.String(length=64), nullable=True),
        sa.Column("client_ip", sa.String(length=64), nullable=True),
        sa.Column("shell", sa.String(length=255), nullable=True),
        sa.Column("agent_pid", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["host_id"], ["hosts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_host_terminal_sessions_host_id"), "host_terminal_sessions", ["host_id"], unique=False)
    op.create_table(
        "webhook_deliveries",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("webhook_id", sa.UUID(), nullable=False),
        sa.Column("system_event_id", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="3", nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(), nullable=True),
        sa.Column("last_http_status", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["system_event_id"], ["system_events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["webhook_id"], ["webhooks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("webhook_id", "system_event_id", name="uq_webhook_deliveries_webhook_system_event"),
    )
    op.create_index(op.f("ix_webhook_deliveries_event_type"), "webhook_deliveries", ["event_type"], unique=False)
    op.create_index(op.f("ix_webhook_deliveries_status"), "webhook_deliveries", ["status"], unique=False)
    op.create_index(
        "ix_webhook_deliveries_status_next_retry_at", "webhook_deliveries", ["status", "next_retry_at"], unique=False
    )
    op.create_index(
        op.f("ix_webhook_deliveries_system_event_id"), "webhook_deliveries", ["system_event_id"], unique=False
    )
    op.create_index(op.f("ix_webhook_deliveries_webhook_id"), "webhook_deliveries", ["webhook_id"], unique=False)
    op.create_table(
        "agent_reconfigure_outbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("accepting_new_sessions", sa.Boolean(), nullable=False),
        sa.Column("stop_pending", sa.Boolean(), nullable=False),
        sa.Column("grid_run_id", sa.UUID(), nullable=True),
        sa.Column("reconciled_generation", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivery_attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("abandoned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("abandoned_reason", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_reconfigure_outbox_device_id"), "agent_reconfigure_outbox", ["device_id"], unique=False
    )
    op.create_index(
        "ix_agent_reconfigure_outbox_undelivered",
        "agent_reconfigure_outbox",
        ["device_id", "delivered_at"],
        unique=False,
    )
    op.create_table(
        "appium_nodes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("grid_url", sa.String(), nullable=False),
        sa.Column("pid", sa.Integer(), nullable=True),
        sa.Column("container_id", sa.String(), nullable=True),
        sa.Column("active_connection_target", sa.String(), nullable=True),
        sa.Column(
            "desired_state", sa.Enum("running", "stopped", name="nodestate"), server_default="stopped", nullable=False
        ),
        sa.Column("desired_port", sa.Integer(), nullable=True),
        sa.Column("desired_grid_run_id", sa.UUID(), nullable=True),
        sa.Column("accepting_new_sessions", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("stop_pending", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("generation", sa.Integer(), server_default="0", nullable=False),
        sa.Column("transition_token", sa.UUID(), nullable=True),
        sa.Column("transition_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("grid_run_id", sa.UUID(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("live_capabilities", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("consecutive_health_failures", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_health_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("health_running", sa.Boolean(), nullable=True),
        sa.Column("health_state", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "desired_state = 'running' OR desired_port IS NULL", name="ck_appium_nodes_desired_port_requires_running"
        ),
        sa.CheckConstraint("desired_state IN ('running', 'stopped')", name="ck_appium_nodes_desired_state"),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id"),
    )
    op.create_index(op.f("ix_appium_nodes_desired_grid_run_id"), "appium_nodes", ["desired_grid_run_id"], unique=False)
    op.create_table(
        "config_audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("previous_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("changed_by", sa.String(), nullable=True),
        sa.Column("changed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_config_audit_logs_device_id"), "config_audit_logs", ["device_id"], unique=False)
    op.create_table(
        "device_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "health_check_fail",
                "connectivity_lost",
                "node_crash",
                "node_restart",
                "hardware_health_changed",
                "connectivity_restored",
                "lifecycle_deferred_stop",
                "lifecycle_auto_stopped",
                "lifecycle_recovery_suppressed",
                "lifecycle_recovery_failed",
                "lifecycle_recovery_backoff",
                "lifecycle_recovered",
                "lifecycle_run_excluded",
                "lifecycle_run_restored",
                "lifecycle_run_cooldown_set",
                "lifecycle_run_cooldown_escalated",
                "maintenance_entered",
                "maintenance_exited",
                "session_started",
                "session_ended",
                "auto_stopped",
                "desired_state_changed",
                name="deviceeventtype",
            ),
            nullable=False,
        ),
        sa.Column("details", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_device_events_device_id"), "device_events", ["device_id"], unique=False)
    op.create_index("ix_device_events_device_id_created_at", "device_events", ["device_id", "created_at"], unique=False)
    op.create_table(
        "device_group_memberships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["group_id"], ["device_groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "device_id"),
    )
    op.create_table(
        "device_intent_dirty",
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("dirty_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("generation", sa.Integer(), server_default="0", nullable=False),
        sa.Column("reason", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("device_id"),
    )
    op.create_table(
        "device_intents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("axis", sa.String(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["test_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "source", name="uq_device_intent_source"),
    )
    op.create_index(op.f("ix_device_intents_axis"), "device_intents", ["axis"], unique=False)
    op.create_index("ix_device_intents_device_axis", "device_intents", ["device_id", "axis"], unique=False)
    op.create_index(op.f("ix_device_intents_device_id"), "device_intents", ["device_id"], unique=False)
    op.create_index(op.f("ix_device_intents_expires_at"), "device_intents", ["expires_at"], unique=False)
    op.create_index(op.f("ix_device_intents_run_id"), "device_intents", ["run_id"], unique=False)
    op.create_index(op.f("ix_device_intents_source"), "device_intents", ["source"], unique=False)
    op.create_table(
        "device_reservations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("identity_value", sa.String(), nullable=False),
        sa.Column("connection_target", sa.String(), nullable=True),
        sa.Column("pack_id", sa.String(), nullable=False),
        sa.Column("platform_id", sa.String(), nullable=False),
        sa.Column("platform_label", sa.String(), nullable=True),
        sa.Column("os_version", sa.String(), nullable=False),
        sa.Column("host_ip", sa.String(), nullable=True),
        sa.Column("excluded", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("exclusion_reason", sa.String(), nullable=True),
        sa.Column("excluded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("excluded_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cooldown_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["test_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_device_reservations_device_id"), "device_reservations", ["device_id"], unique=False)
    op.create_index(op.f("ix_device_reservations_run_id"), "device_reservations", ["run_id"], unique=False)
    op.create_index(
        "uq_device_reservations_active_device",
        "device_reservations",
        ["device_id"],
        unique=True,
        postgresql_where=sa.text("released_at IS NULL"),
    )
    op.create_table(
        "device_test_data_audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("previous_test_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_test_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("changed_by", sa.String(), nullable=True),
        sa.Column("changed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_device_test_data_audit_logs_device_id"), "device_test_data_audit_logs", ["device_id"], unique=False
    )
    op.create_table(
        "driver_pack_features",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("pack_release_id", sa.UUID(), nullable=False),
        sa.Column("manifest_feature_id", sa.String(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["pack_release_id"], ["driver_pack_releases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pack_release_id", "manifest_feature_id", name="driver_pack_features_release_feature_uq"),
    )
    op.create_table(
        "driver_pack_platforms",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("pack_release_id", sa.UUID(), nullable=False),
        sa.Column("manifest_platform_id", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("automation_name", sa.String(), nullable=False),
        sa.Column("appium_platform_name", sa.String(), nullable=False),
        sa.Column("device_types", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("connection_types", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("grid_slots", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["pack_release_id"], ["driver_pack_releases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "pack_release_id", "manifest_platform_id", name="driver_pack_platforms_release_platform_uq"
        ),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=True),
        sa.Column("test_name", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.Enum("running", "passed", "failed", "error", name="sessionstatus"), nullable=False),
        sa.Column("requested_pack_id", sa.String(), nullable=True),
        sa.Column("requested_platform_id", sa.String(), nullable=True),
        sa.Column(
            "requested_device_type", sa.Enum("real_device", "emulator", "simulator", name="devicetype"), nullable=True
        ),
        sa.Column(
            "requested_connection_type", sa.Enum("usb", "network", "virtual", name="connectiontype"), nullable=True
        ),
        sa.Column("requested_capabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_type", sa.String(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["test_runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_sessions_device_id_started_at", "sessions", ["device_id", "started_at"], unique=False)
    op.create_index(op.f("ix_sessions_run_id"), "sessions", ["run_id"], unique=False)
    op.create_index(op.f("ix_sessions_session_id"), "sessions", ["session_id"], unique=False)
    op.create_index(
        "ux_sessions_session_id_running",
        "sessions",
        ["session_id"],
        unique=True,
        postgresql_where=sa.text("status = 'running' AND ended_at IS NULL"),
    )
    op.create_table(
        "appium_node_resource_claims",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("host_id", sa.UUID(), nullable=False),
        sa.Column("capability_key", sa.String(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["node_id"], ["appium_nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("host_id", "capability_key", "port", name="uq_appium_node_resource_claims_port"),
    )
    op.create_index("ix_appium_node_resource_claims_node_id", "appium_node_resource_claims", ["node_id"], unique=False)
    op.create_index(
        "uq_appium_node_resource_claims_managed_node",
        "appium_node_resource_claims",
        ["node_id", "capability_key"],
        unique=True,
        postgresql_where=sa.text("node_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_appium_node_resource_claims_managed_node",
        table_name="appium_node_resource_claims",
        postgresql_where=sa.text("node_id IS NOT NULL"),
    )
    op.drop_index("ix_appium_node_resource_claims_node_id", table_name="appium_node_resource_claims")
    op.drop_table("appium_node_resource_claims")
    op.drop_index(
        "ux_sessions_session_id_running",
        table_name="sessions",
        postgresql_where=sa.text("status = 'running' AND ended_at IS NULL"),
    )
    op.drop_index(op.f("ix_sessions_session_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_run_id"), table_name="sessions")
    op.drop_index("ix_sessions_device_id_started_at", table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("driver_pack_platforms")
    op.drop_table("driver_pack_features")
    op.drop_index(op.f("ix_device_test_data_audit_logs_device_id"), table_name="device_test_data_audit_logs")
    op.drop_table("device_test_data_audit_logs")
    op.drop_index(
        "uq_device_reservations_active_device",
        table_name="device_reservations",
        postgresql_where=sa.text("released_at IS NULL"),
    )
    op.drop_index(op.f("ix_device_reservations_run_id"), table_name="device_reservations")
    op.drop_index(op.f("ix_device_reservations_device_id"), table_name="device_reservations")
    op.drop_table("device_reservations")
    op.drop_index(op.f("ix_device_intents_source"), table_name="device_intents")
    op.drop_index(op.f("ix_device_intents_run_id"), table_name="device_intents")
    op.drop_index(op.f("ix_device_intents_expires_at"), table_name="device_intents")
    op.drop_index(op.f("ix_device_intents_device_id"), table_name="device_intents")
    op.drop_index("ix_device_intents_device_axis", table_name="device_intents")
    op.drop_index(op.f("ix_device_intents_axis"), table_name="device_intents")
    op.drop_table("device_intents")
    op.drop_table("device_intent_dirty")
    op.drop_table("device_group_memberships")
    op.drop_index("ix_device_events_device_id_created_at", table_name="device_events")
    op.drop_index(op.f("ix_device_events_device_id"), table_name="device_events")
    op.drop_table("device_events")
    op.drop_index(op.f("ix_config_audit_logs_device_id"), table_name="config_audit_logs")
    op.drop_table("config_audit_logs")
    op.drop_index(op.f("ix_appium_nodes_desired_grid_run_id"), table_name="appium_nodes")
    op.drop_table("appium_nodes")
    op.drop_index("ix_agent_reconfigure_outbox_undelivered", table_name="agent_reconfigure_outbox")
    op.drop_index(op.f("ix_agent_reconfigure_outbox_device_id"), table_name="agent_reconfigure_outbox")
    op.drop_table("agent_reconfigure_outbox")
    op.drop_index(op.f("ix_webhook_deliveries_webhook_id"), table_name="webhook_deliveries")
    op.drop_index(op.f("ix_webhook_deliveries_system_event_id"), table_name="webhook_deliveries")
    op.drop_index("ix_webhook_deliveries_status_next_retry_at", table_name="webhook_deliveries")
    op.drop_index(op.f("ix_webhook_deliveries_status"), table_name="webhook_deliveries")
    op.drop_index(op.f("ix_webhook_deliveries_event_type"), table_name="webhook_deliveries")
    op.drop_table("webhook_deliveries")
    op.drop_index(op.f("ix_host_terminal_sessions_host_id"), table_name="host_terminal_sessions")
    op.drop_table("host_terminal_sessions")
    op.drop_table("host_runtime_installations")
    op.drop_index("ix_host_resource_samples_recorded_at", table_name="host_resource_samples")
    op.drop_index("ix_host_resource_samples_host_id_recorded_at", table_name="host_resource_samples")
    op.drop_table("host_resource_samples")
    op.drop_table("host_plugin_runtime_statuses")
    op.drop_table("host_pack_installations")
    op.drop_index(op.f("ix_host_pack_feature_status_host_id"), table_name="host_pack_feature_status")
    op.drop_table("host_pack_feature_status")
    op.drop_table("host_pack_doctor_results")
    op.drop_table("driver_pack_releases")
    op.drop_index(
        "uq_devices_identity_scheme_value_global",
        table_name="devices",
        postgresql_where=sa.text("identity_scope = 'global'"),
    )
    op.drop_index(
        "uq_devices_host_identity_scheme_value",
        table_name="devices",
        postgresql_where=sa.text("identity_scope = 'host'"),
    )
    op.drop_index("ix_devices_test_data_gin", table_name="devices")
    op.drop_index("ix_devices_tags_gin", table_name="devices")
    op.drop_index("ix_devices_search_vector_gin", table_name="devices")
    op.drop_index("ix_devices_pack_platform", table_name="devices")
    op.drop_index("ix_devices_device_config_gin", table_name="devices")
    op.drop_index(op.f("ix_devices_identity_value"), table_name="devices")
    op.drop_table("devices")
    op.drop_table("webhooks")
    op.drop_table("test_runs")
    op.drop_index("ix_system_events_type_created_at", table_name="system_events")
    op.drop_index(op.f("ix_system_events_type"), table_name="system_events")
    op.drop_index("ix_system_events_data_gin", table_name="system_events")
    op.drop_index(op.f("ix_system_events_event_id"), table_name="system_events")
    op.drop_table("system_events")
    op.drop_index(op.f("ix_settings_key"), table_name="settings")
    op.drop_table("settings")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_scheduled_at"), table_name="jobs")
    op.drop_index("ix_jobs_kind_status_scheduled_at", table_name="jobs")
    op.drop_index(op.f("ix_jobs_kind"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_hosts_hostname"), table_name="hosts")
    op.drop_table("hosts")
    op.drop_table("driver_packs")
    op.drop_index("ix_device_groups_filters_gin", table_name="device_groups")
    op.drop_table("device_groups")
    op.drop_index(op.f("ix_control_plane_state_entries_namespace"), table_name="control_plane_state_entries")
    op.drop_index(op.f("ix_control_plane_state_entries_key"), table_name="control_plane_state_entries")
    op.drop_table("control_plane_state_entries")
    op.drop_table("control_plane_leader_heartbeats")
    op.drop_index(op.f("ix_appium_plugins_name"), table_name="appium_plugins")
    op.drop_table("appium_plugins")
    op.drop_index("ix_analytics_capacity_snapshots_captured_at", table_name="analytics_capacity_snapshots")
    op.drop_table("analytics_capacity_snapshots")
    op.execute("DROP EXTENSION IF EXISTS btree_gist")
    # ### end Alembic commands ###
