"""naming-convention-baseline

Revision ID: e827486cd633
Revises: 53063d67b14c
Create Date: 2026-05-15 14:23:43.756998

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e827486cd633"
down_revision: str | None = "53063d67b14c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_reconfigure_outbox_device_id"), table_name="agent_reconfigure_outbox")
    op.create_index(
        op.f("agent_reconfigure_outbox_device_id_idx"), "agent_reconfigure_outbox", ["device_id"], unique=False
    )
    op.drop_index(op.f("ix_appium_nodes_desired_grid_run_id"), table_name="appium_nodes")
    op.create_index(op.f("appium_nodes_desired_grid_run_id_idx"), "appium_nodes", ["desired_grid_run_id"], unique=False)
    op.drop_index(op.f("ix_appium_plugins_name"), table_name="appium_plugins")
    op.create_index(op.f("appium_plugins_name_idx"), "appium_plugins", ["name"], unique=True)
    op.drop_index(op.f("ix_config_audit_logs_device_id"), table_name="config_audit_logs")
    op.create_index(op.f("config_audit_logs_device_id_idx"), "config_audit_logs", ["device_id"], unique=False)
    op.drop_index(op.f("ix_control_plane_state_entries_key"), table_name="control_plane_state_entries")
    op.drop_index(op.f("ix_control_plane_state_entries_namespace"), table_name="control_plane_state_entries")
    op.create_index(op.f("control_plane_state_entries_key_idx"), "control_plane_state_entries", ["key"], unique=False)
    op.create_index(
        op.f("control_plane_state_entries_namespace_idx"), "control_plane_state_entries", ["namespace"], unique=False
    )
    op.drop_index(op.f("ix_device_events_device_id"), table_name="device_events")
    op.create_index(op.f("device_events_device_id_idx"), "device_events", ["device_id"], unique=False)
    op.drop_constraint(
        op.f("device_group_memberships_group_id_device_id_key"), "device_group_memberships", type_="unique"
    )
    op.create_unique_constraint(
        op.f("device_group_memberships_group_id_key"), "device_group_memberships", ["group_id", "device_id"]
    )
    op.drop_index(op.f("ix_device_intents_axis"), table_name="device_intents")
    op.drop_index(op.f("ix_device_intents_device_id"), table_name="device_intents")
    op.drop_index(op.f("ix_device_intents_expires_at"), table_name="device_intents")
    op.drop_index(op.f("ix_device_intents_run_id"), table_name="device_intents")
    op.drop_index(op.f("ix_device_intents_source"), table_name="device_intents")
    op.create_index(op.f("device_intents_axis_idx"), "device_intents", ["axis"], unique=False)
    op.create_index(op.f("device_intents_device_id_idx"), "device_intents", ["device_id"], unique=False)
    op.create_index(op.f("device_intents_expires_at_idx"), "device_intents", ["expires_at"], unique=False)
    op.create_index(op.f("device_intents_run_id_idx"), "device_intents", ["run_id"], unique=False)
    op.create_index(op.f("device_intents_source_idx"), "device_intents", ["source"], unique=False)
    op.drop_index(op.f("ix_device_reservations_device_id"), table_name="device_reservations")
    op.drop_index(op.f("ix_device_reservations_run_id"), table_name="device_reservations")
    op.create_index(op.f("device_reservations_device_id_idx"), "device_reservations", ["device_id"], unique=False)
    op.create_index(op.f("device_reservations_run_id_idx"), "device_reservations", ["run_id"], unique=False)
    op.drop_index(op.f("ix_device_test_data_audit_logs_device_id"), table_name="device_test_data_audit_logs")
    op.create_index(
        op.f("device_test_data_audit_logs_device_id_idx"), "device_test_data_audit_logs", ["device_id"], unique=False
    )
    op.drop_index(op.f("ix_devices_identity_value"), table_name="devices")
    op.create_index(op.f("devices_identity_value_idx"), "devices", ["identity_value"], unique=False)
    op.drop_index(op.f("ix_host_pack_feature_status_host_id"), table_name="host_pack_feature_status")
    op.create_index(op.f("host_pack_feature_status_host_id_idx"), "host_pack_feature_status", ["host_id"], unique=False)
    op.drop_index(op.f("ix_host_terminal_sessions_host_id"), table_name="host_terminal_sessions")
    op.create_index(op.f("host_terminal_sessions_host_id_idx"), "host_terminal_sessions", ["host_id"], unique=False)
    op.drop_index(op.f("ix_hosts_hostname"), table_name="hosts")
    op.create_index(op.f("hosts_hostname_idx"), "hosts", ["hostname"], unique=True)
    op.drop_index(op.f("ix_jobs_kind"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_scheduled_at"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.create_index(op.f("jobs_kind_idx"), "jobs", ["kind"], unique=False)
    op.create_index(op.f("jobs_scheduled_at_idx"), "jobs", ["scheduled_at"], unique=False)
    op.create_index(op.f("jobs_status_idx"), "jobs", ["status"], unique=False)
    op.drop_index(op.f("ix_sessions_run_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_session_id"), table_name="sessions")
    op.create_index(op.f("sessions_run_id_idx"), "sessions", ["run_id"], unique=False)
    op.create_index(op.f("sessions_session_id_idx"), "sessions", ["session_id"], unique=False)
    op.drop_index(op.f("ix_settings_key"), table_name="settings")
    op.create_index(op.f("settings_key_idx"), "settings", ["key"], unique=True)
    op.drop_index(op.f("ix_system_events_event_id"), table_name="system_events")
    op.drop_index(op.f("ix_system_events_type"), table_name="system_events")
    op.create_index(op.f("system_events_event_id_idx"), "system_events", ["event_id"], unique=True)
    op.create_index(op.f("system_events_type_idx"), "system_events", ["type"], unique=False)
    op.drop_index(op.f("ix_webhook_deliveries_event_type"), table_name="webhook_deliveries")
    op.drop_index(op.f("ix_webhook_deliveries_status"), table_name="webhook_deliveries")
    op.drop_index(op.f("ix_webhook_deliveries_system_event_id"), table_name="webhook_deliveries")
    op.drop_index(op.f("ix_webhook_deliveries_webhook_id"), table_name="webhook_deliveries")
    op.create_index(op.f("webhook_deliveries_event_type_idx"), "webhook_deliveries", ["event_type"], unique=False)
    op.create_index(op.f("webhook_deliveries_status_idx"), "webhook_deliveries", ["status"], unique=False)
    op.create_index(
        op.f("webhook_deliveries_system_event_id_idx"), "webhook_deliveries", ["system_event_id"], unique=False
    )
    op.create_index(op.f("webhook_deliveries_webhook_id_idx"), "webhook_deliveries", ["webhook_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("webhook_deliveries_webhook_id_idx"), table_name="webhook_deliveries")
    op.drop_index(op.f("webhook_deliveries_system_event_id_idx"), table_name="webhook_deliveries")
    op.drop_index(op.f("webhook_deliveries_status_idx"), table_name="webhook_deliveries")
    op.drop_index(op.f("webhook_deliveries_event_type_idx"), table_name="webhook_deliveries")
    op.create_index(op.f("ix_webhook_deliveries_webhook_id"), "webhook_deliveries", ["webhook_id"], unique=False)
    op.create_index(
        op.f("ix_webhook_deliveries_system_event_id"), "webhook_deliveries", ["system_event_id"], unique=False
    )
    op.create_index(op.f("ix_webhook_deliveries_status"), "webhook_deliveries", ["status"], unique=False)
    op.create_index(op.f("ix_webhook_deliveries_event_type"), "webhook_deliveries", ["event_type"], unique=False)
    op.drop_index(op.f("system_events_type_idx"), table_name="system_events")
    op.drop_index(op.f("system_events_event_id_idx"), table_name="system_events")
    op.create_index(op.f("ix_system_events_type"), "system_events", ["type"], unique=False)
    op.create_index(op.f("ix_system_events_event_id"), "system_events", ["event_id"], unique=True)
    op.drop_index(op.f("settings_key_idx"), table_name="settings")
    op.create_index(op.f("ix_settings_key"), "settings", ["key"], unique=True)
    op.drop_index(op.f("sessions_session_id_idx"), table_name="sessions")
    op.drop_index(op.f("sessions_run_id_idx"), table_name="sessions")
    op.create_index(op.f("ix_sessions_session_id"), "sessions", ["session_id"], unique=False)
    op.create_index(op.f("ix_sessions_run_id"), "sessions", ["run_id"], unique=False)
    op.drop_index(op.f("jobs_status_idx"), table_name="jobs")
    op.drop_index(op.f("jobs_scheduled_at_idx"), table_name="jobs")
    op.drop_index(op.f("jobs_kind_idx"), table_name="jobs")
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_index(op.f("ix_jobs_scheduled_at"), "jobs", ["scheduled_at"], unique=False)
    op.create_index(op.f("ix_jobs_kind"), "jobs", ["kind"], unique=False)
    op.drop_index(op.f("hosts_hostname_idx"), table_name="hosts")
    op.create_index(op.f("ix_hosts_hostname"), "hosts", ["hostname"], unique=True)
    op.drop_index(op.f("host_terminal_sessions_host_id_idx"), table_name="host_terminal_sessions")
    op.create_index(op.f("ix_host_terminal_sessions_host_id"), "host_terminal_sessions", ["host_id"], unique=False)
    op.drop_index(op.f("host_pack_feature_status_host_id_idx"), table_name="host_pack_feature_status")
    op.create_index(op.f("ix_host_pack_feature_status_host_id"), "host_pack_feature_status", ["host_id"], unique=False)
    op.drop_index(op.f("devices_identity_value_idx"), table_name="devices")
    op.create_index(op.f("ix_devices_identity_value"), "devices", ["identity_value"], unique=False)
    op.drop_index(op.f("device_test_data_audit_logs_device_id_idx"), table_name="device_test_data_audit_logs")
    op.create_index(
        op.f("ix_device_test_data_audit_logs_device_id"), "device_test_data_audit_logs", ["device_id"], unique=False
    )
    op.drop_index(op.f("device_reservations_run_id_idx"), table_name="device_reservations")
    op.drop_index(op.f("device_reservations_device_id_idx"), table_name="device_reservations")
    op.create_index(op.f("ix_device_reservations_run_id"), "device_reservations", ["run_id"], unique=False)
    op.create_index(op.f("ix_device_reservations_device_id"), "device_reservations", ["device_id"], unique=False)
    op.drop_index(op.f("device_intents_source_idx"), table_name="device_intents")
    op.drop_index(op.f("device_intents_run_id_idx"), table_name="device_intents")
    op.drop_index(op.f("device_intents_expires_at_idx"), table_name="device_intents")
    op.drop_index(op.f("device_intents_device_id_idx"), table_name="device_intents")
    op.drop_index(op.f("device_intents_axis_idx"), table_name="device_intents")
    op.create_index(op.f("ix_device_intents_source"), "device_intents", ["source"], unique=False)
    op.create_index(op.f("ix_device_intents_run_id"), "device_intents", ["run_id"], unique=False)
    op.create_index(op.f("ix_device_intents_expires_at"), "device_intents", ["expires_at"], unique=False)
    op.create_index(op.f("ix_device_intents_device_id"), "device_intents", ["device_id"], unique=False)
    op.create_index(op.f("ix_device_intents_axis"), "device_intents", ["axis"], unique=False)
    op.drop_constraint(op.f("device_group_memberships_group_id_key"), "device_group_memberships", type_="unique")
    op.create_unique_constraint(
        op.f("device_group_memberships_group_id_device_id_key"),
        "device_group_memberships",
        ["group_id", "device_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("device_events_device_id_idx"), table_name="device_events")
    op.create_index(op.f("ix_device_events_device_id"), "device_events", ["device_id"], unique=False)
    op.drop_index(op.f("control_plane_state_entries_namespace_idx"), table_name="control_plane_state_entries")
    op.drop_index(op.f("control_plane_state_entries_key_idx"), table_name="control_plane_state_entries")
    op.create_index(
        op.f("ix_control_plane_state_entries_namespace"), "control_plane_state_entries", ["namespace"], unique=False
    )
    op.create_index(op.f("ix_control_plane_state_entries_key"), "control_plane_state_entries", ["key"], unique=False)
    op.drop_index(op.f("config_audit_logs_device_id_idx"), table_name="config_audit_logs")
    op.create_index(op.f("ix_config_audit_logs_device_id"), "config_audit_logs", ["device_id"], unique=False)
    op.drop_index(op.f("appium_plugins_name_idx"), table_name="appium_plugins")
    op.create_index(op.f("ix_appium_plugins_name"), "appium_plugins", ["name"], unique=True)
    op.drop_index(op.f("appium_nodes_desired_grid_run_id_idx"), table_name="appium_nodes")
    op.create_index(op.f("ix_appium_nodes_desired_grid_run_id"), "appium_nodes", ["desired_grid_run_id"], unique=False)
    op.drop_index(op.f("agent_reconfigure_outbox_device_id_idx"), table_name="agent_reconfigure_outbox")
    op.create_index(
        op.f("ix_agent_reconfigure_outbox_device_id"), "agent_reconfigure_outbox", ["device_id"], unique=False
    )
    # ### end Alembic commands ###
