"""Plugins domain Protocol definitions."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Protocol, runtime_checkable

if TYPE_CHECKING:
    import uuid

    from sqlalchemy.ext.asyncio import AsyncSession

    from app.hosts.models import Host
    from app.plugins.models import AppiumPlugin
    from app.plugins.schemas import PluginCreate, PluginUpdate


@runtime_checkable
class PluginProtocol(Protocol):
    async def list_plugins(self, db: AsyncSession) -> list[AppiumPlugin]: ...
    async def get_plugin(self, db: AsyncSession, plugin_id: uuid.UUID) -> AppiumPlugin | None: ...
    async def create_plugin(self, db: AsyncSession, data: PluginCreate) -> AppiumPlugin: ...
    async def update_plugin(
        self, db: AsyncSession, plugin_id: uuid.UUID, data: PluginUpdate
    ) -> AppiumPlugin | None: ...
    async def delete_plugin(self, db: AsyncSession, plugin_id: uuid.UUID) -> bool: ...
    async def get_host_plugin_statuses(self, host: Host, plugins: list[AppiumPlugin]) -> list[dict[str, Any]]: ...
    async def sync_host_plugins(self, host: Host, plugins: list[AppiumPlugin]) -> dict[str, Any]: ...
    async def sync_all_host_plugins(self, db: AsyncSession) -> dict[str, Any]: ...
    async def auto_sync_host_plugins(self, host: Host, plugins: list[AppiumPlugin]) -> None: ...
